"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { askQuestion,checkHealth,deleteSession,forgetMemory,listSessions,myMemories,rememberForMe,sessionHistory,submitFeedback,submitImplicitFeedback,type ChatResult,type DeptRoute,type SessionSummary,type User,type UserMemoryItem } from "@/lib/api";
import Icon from "./Icon"; import styles from "./Chat.module.css";
interface Message { role:"user"|"assistant";content:string;citations?:ChatResult["citations"];error?:boolean;query?:string;rated?:"up"|"down";route?:DeptRoute|null;meta?:Pick<ChatResult,"confidence"|"intent_type"|"verification"|"retrieved_count"> }
const SUGGESTIONS=["What safety precautions should staff take during a rainstorm?","What are the complete steps of the psychological assessment?","What are the luggage storage requirements at the Sino-French Institute?","What do I need to prepare for the graduate thesis proposal defense?"];
function makeSessionId(){return typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID():Date.now().toString()}
export default function Chat({user,onLogout}:{user:User;onLogout:()=>void}){
 const [messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[online,setOnline]=useState<boolean|null>(null);
 const [sessionId,setSessionId]=useState<string|null>(null),[sessions,setSessions]=useState<SessionSummary[]>([]),[activeSession,setActiveSession]=useState<string|null>(null),[sidebarOpen,setSidebarOpen]=useState(true);
 const [memoryOpen,setMemoryOpen]=useState(false),[memories,setMemories]=useState<UserMemoryItem[]>([]),[memoryKey,setMemoryKey]=useState("answer_style"),[memoryValue,setMemoryValue]=useState("Concise answers with bullet points"),[memoryBusy,setMemoryBusy]=useState(false);
 const listRef=useRef<HTMLDivElement>(null),latestUnratedRef=useRef<{query:string;answer:string}|null>(null);
 const welcome=`Hello, ${user.name}. I retrieve evidence from policies currently in effect, generate and verify answers with the pi Agent, and keep traceable citations.`;
 useEffect(()=>{checkHealth().then(setOnline)},[]);useEffect(()=>setMessages([{role:"assistant",content:welcome}]),[user.id,welcome]);useEffect(()=>listRef.current?.scrollTo({top:listRef.current.scrollHeight,behavior:"smooth"}),[messages,busy]);
 const refreshSessions=useCallback(()=>listSessions().then(setSessions).catch(()=>undefined),[]);useEffect(()=>{refreshSessions()},[refreshSessions]);
 const loadMemories=useCallback(()=>myMemories().then(setMemories).catch(()=>undefined),[]);useEffect(()=>{if(memoryOpen)loadMemories()},[memoryOpen,loadMemories]);
 const startNewChat=useCallback(()=>{setSessionId(makeSessionId());setActiveSession(null);setMessages([{role:"assistant",content:welcome}])},[welcome]);
 const loadSession=useCallback(async(sid:string)=>{try{const h=await sessionHistory(sid);setSessionId(sid);setActiveSession(sid);setMessages(h.length?h as Message[]:[{role:"assistant",content:welcome}])}catch{}},[welcome]);
 const removeSession=useCallback(async(sid:string)=>{try{await deleteSession(sid)}catch{}setSessions(s=>s.filter(x=>x.session_id!==sid));if(sid===sessionId)startNewChat()},[sessionId,startNewChat]);
 const send=useCallback(async(forced?:string)=>{const query=(forced??input).trim();if(!query||busy)return;const sid=sessionId??makeSessionId();setMessages(m=>[...m,{role:"user",content:query}]);setInput("");setBusy(true);try{const r=await askQuestion({query,session_id:sid,dept_ids:null});const finalSid=r.session_id||sid;setSessionId(finalSid);setActiveSession(finalSid);setMessages(m=>[...m,{role:"assistant",content:r.answer,citations:r.citations,query,route:r.route,meta:{confidence:r.confidence,intent_type:r.intent_type,verification:r.verification,retrieved_count:r.retrieved_count}}]);latestUnratedRef.current={query,answer:r.answer};refreshSessions()}catch(e){setMessages(m=>[...m,{role:"assistant",content:`Request failed: ${e instanceof Error?e.message:String(e)}`,error:true}])}finally{setBusy(false)}},[input,busy,sessionId,refreshSessions]);
 const rate=useCallback(async(i:number,signal:"up"|"down")=>{const msg=messages[i];if(!msg||msg.role!=="assistant"||msg.rated||!msg.query)return;setMessages(m=>m.map((x,j)=>j===i?{...x,rated:signal}:x));latestUnratedRef.current=null;try{await submitFeedback({session_id:sessionId||"",query:msg.query,answer:msg.content,signal})}catch{}},[messages,sessionId]);
 const copyAnswer=useCallback(async(m:Message)=>{await navigator.clipboard.writeText(m.content);if(sessionId&&m.query)submitImplicitFeedback({session_id:sessionId,signal:"copy",query:m.query,answer:m.content}).catch(()=>undefined)},[sessionId]);
 useEffect(()=>()=>{const p=latestUnratedRef.current;if(sessionId&&p)submitImplicitFeedback({session_id:sessionId,signal:"abandon",query:p.query,answer:p.answer}).catch(()=>undefined)},[sessionId]);
 async function addMemory(){if(!memoryKey.trim()||!memoryValue.trim())return;setMemoryBusy(true);try{await rememberForMe({key:memoryKey.trim(),value:memoryValue.trim(),category:"preference",consent:true});await loadMemories()}finally{setMemoryBusy(false)}}
 async function removeMemory(id:string){await forgetMemory(id);await loadMemories()}
 const hasConversation=messages.some(m=>m.role==="user");
 return <div className={styles.app}>
  <aside className={`${styles.sidebar} ${sidebarOpen?"":styles.sidebarClosed}`}>
   <div className={styles.sideBrand}><span>C</span><div><b>Clausewise</b><small>TRUSTED QA</small></div></div>
   <button className={styles.newChatBtn} onClick={startNewChat}><Icon name="plus" size={17}/>New conversation</button>
   <div className={styles.sidebarBody}><div className={styles.sectionTitle}>Recent conversations <em>{sessions.length}</em></div>{sessions.length===0&&<div className={styles.empty}>Ask a question to start building episodic memory</div>}{sessions.map(s=><div key={s.session_id} className={`${styles.sessionItem} ${activeSession===s.session_id?styles.sessionActive:""}`} onClick={()=>loadSession(s.session_id)}><Icon name="chat" size={14}/><span className={styles.sessionTitle}>{s.title||"New conversation"}</span><button onClick={e=>{e.stopPropagation();removeSession(s.session_id)}}><Icon name="trash" size={13}/></button></div>)}</div>
   <button className={styles.memoryEntry} onClick={()=>setMemoryOpen(true)}><span><Icon name="memory" size={17}/></span><div><b>My long-term memory</b><small>See how the system understands your preferences</small></div><Icon name="arrow" size={14}/></button>
   <div className={styles.sideUser}><div>{user.name.slice(0,1)}</div><span><b>{user.name}</b><small>Student · {user.id}</small></span><button onClick={onLogout}><Icon name="logout" size={15}/></button></div>
  </aside>
  <section className={styles.main}>
   <header className={styles.header}><div className={styles.left}><button className={styles.collapseBtn} onClick={()=>setSidebarOpen(v=>!v)}><Icon name="menu" size={18}/></button><div><b>Policy Q&amp;A Workspace</b><small>Trusted answers based on official documents</small></div></div><div className={styles.right}><span className={`${styles.status} ${online?styles.ok:online===false?styles.err:""}`}><i/>{online===null?"Connecting":online?"Fact and Agent services online":"Backend unavailable"}</span><span className={styles.engine}>PI AGENT ENGINE</span></div></header>
   <main className={`${styles.chat} ${!hasConversation?styles.chatEmpty:""}`} ref={listRef}>
    {!hasConversation&&<div className={styles.welcome}><div className={styles.welcomeMark}><Icon name="spark" size={25}/></div><span className={styles.welcomeKicker}>ASK WITH EVIDENCE</span><h1>Which policy would you like to know about today?</h1><p>{welcome}</p><div className={styles.suggestions}>{SUGGESTIONS.map((s,i)=><button key={s} onClick={()=>send(s)}><span>0{i+1}</span>{s}<Icon name="arrow" size={14}/></button>)}</div><div className={styles.flow}><span><Icon name="search" size={14}/>Hybrid retrieval</span><i>→</i><span><Icon name="agent" size={14}/>Agent generation</span><i>→</i><span><Icon name="shield" size={14}/>Trusted verification</span><i>→</i><span><Icon name="file" size={14}/>Source citations</span></div></div>}
    {hasConversation&&messages.map((m,i)=><article key={i} className={`${styles.msgRow} ${m.role==="user"?styles.userRow:styles.assistantRow}`}><div className={styles.roleAvatar}>{m.role==="user"?"You":<Icon name="spark" size={17}/>}</div><div className={`${styles.msg} ${m.error?styles.errorText:""}`}><div className={styles.msgHead}><b>{m.role==="user"?"Your question":"Clausewise's answer"}</b>{m.meta&&<span className={m.meta.verification?.passed?styles.verified:styles.warning}><Icon name="shield" size={13}/>{m.meta.verification?.passed?`Verified ${Math.round((m.meta.verification.score||0)*100)}%`:"Needs review"}</span>}</div><div className={styles.content}>{m.content}</div>
     {m.meta&&<div className={styles.reasoning}><span><Icon name="search" size={13}/>{m.meta.retrieved_count} pieces of evidence retrieved</span><span><Icon name="agent" size={13}/>{m.meta.intent_type}</span><span><Icon name="activity" size={13}/>Answer confidence {Math.round((m.meta.confidence||0)*100)}%</span></div>}
     {m.route?.dept_names?.length?<div className={styles.route}><Icon name="building" size={14}/><span>Smart routing</span><b>{m.route.dept_names.join(", ")}</b><small>{m.route.reasons?.[0]}</small></div>:null}
     {m.citations?.length?<details className={styles.citations}><summary><Icon name="file" size={14}/>View {m.citations.length} policy sources <Icon name="arrow" size={13}/></summary><div>{m.citations.map((c,j)=><div key={`${c.doc_id}-${j}`} className={styles.cite}><span>{j+1}</span><div><b>{c.doc_title||c.doc_id}</b><small>{c.section_path?.join(" / ")||`Document chunk #${c.chunk_index}`}</small><p>{c.snippet}</p></div></div>)}</div></details>:null}
     {m.role==="assistant"&&m.query&&!m.error&&<div className={styles.rating}><span>Did this answer solve your problem?</span><button className={m.rated==="up"?styles.ratedUp:""} onClick={()=>rate(i,"up")} disabled={!!m.rated}>Helpful</button><button onClick={()=>copyAnswer(m)}><Icon name="copy" size={13}/>Copy</button><button className={m.rated==="down"?styles.ratedDown:""} onClick={()=>rate(i,"down")} disabled={!!m.rated}>Needs improvement</button></div>}</div></article>)}
    {busy&&<div className={styles.thinking}><span className={styles.thinkingMark}><Icon name="spark" size={17}/></span><div><b>Working on it</b><small>Routing departments · Recalling facts · Running agents · Verifying citations</small><i><em/><em/><em/></i></div></div>}
   </main>
   <footer className={styles.composer}><div className={styles.composerBox}><textarea value={input} rows={1} placeholder="Describe the policy, procedure, or deadline you want to ask about…" onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><button onClick={()=>send()} disabled={busy||!input.trim()}><Icon name="send" size={18}/></button></div><p>Answers rely only on policies in effect · Key conclusions cite sources · Shift + Enter for a new line</p></footer>
  </section>
  {memoryOpen&&<div className={styles.modalBackdrop} onClick={()=>setMemoryOpen(false)}><section className={styles.memoryPanel} onClick={e=>e.stopPropagation()}><header><div><span>USER SEMANTIC MEMORY</span><h2>My long-term memory</h2><p>Only low-sensitivity preferences you explicitly approve are saved; you can view and delete them anytime.</p></div><button onClick={()=>setMemoryOpen(false)}>×</button></header><div className={styles.memoryForm}><input value={memoryKey} onChange={e=>setMemoryKey(e.target.value)} placeholder="Preference name"/><input value={memoryValue} onChange={e=>setMemoryValue(e.target.value)} placeholder="Preference value"/><button onClick={addMemory} disabled={memoryBusy}>{memoryBusy?"Saving":"Remember this preference"}</button></div><div className={styles.memoryNotice}><Icon name="shield" size={15}/>Sensitive information such as ID numbers, passwords, and contact details is never written to long-term memory.</div><div className={styles.memoryList}>{memories.length===0?<div className={styles.memoryEmpty}><Icon name="memory" size={25}/><b>No long-term memory yet</b><small>After you save an answer style or stable preference, it will be used when building future context.</small></div>:memories.map(m=><div key={m._id}><span><Icon name="memory" size={15}/></span><div><b>{m.key}</b><p>{String(m.value)}</p><small>{m.category} · revision {m.revision||1}</small></div><button onClick={()=>removeMemory(m._id)}><Icon name="trash" size={14}/></button></div>)}</div></section></div>}
 </div>
}
